name = "a-action-chatbot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
# Environment variables will be set in Cloudflare dashboard

# Add your Gemini API key as a secret
# Run: wrangler secret put GEMINI_API_KEY
